### ISSUE TITLE
Less ambiguous names

### ISSUE THREAD

**Issue by ParadaCarleton** [voting-tools/pref_voting#100]
A couple of the function names threw me off when I tried using them—
1. Majority winner has also been used to mean Condorcet winner, which could cause some confusion. I've heard this called the Woodall winner or Woodall favorite in the past (since the name seems to be a reference to Woodall's majority criterion, rather than Condorcet's).
2. The specific definition of "spoiler" threw me off quite a bit, since I've always heard it associated with IIA violations. I believe this is the original definition from sports, where it means a weak team—one with no chance of making it into the playoffs—spoiling another team's chances of making the playoffs (by beating them).

**Comment by wesholliday** [comment]
Thanks for the feedback!

1. We changed 'majority' to 'absolute_majority', following Dodgson.

2. We added a citation for the Immunity to Spoilers axiom (https://doi.org/10.1007/s11127-023-01042-3).
