### ISSUE TITLE
Spelling of "Kemeny"/"Kemmeny"

### ISSUE THREAD

**Issue by DominikPeters** [voting-tools/pref_voting#31]
You refer to the "Kemmeny-Young rule" with a double-"m", both in code and in the docs. But Kemeny spells his name with a single "m".

<img width="391" alt="image" src="https://github.com/voting-tools/pref_voting/assets/3543224/cadc2e8a-08f2-4534-af1c-1d108981d246">

https://www.jstor.org/stable/20026529

**Comment by wesholliday** [comment]
Thanks for this good catch!
