### ISSUE TITLE
prefsampling code regarding Euclidean spaces has changed

### ISSUE THREAD

**Issue by DominikPeters** [voting-tools/pref_voting#67]
`EuclideanSpace` is not defined anymore in the current version of the `prefsampling` module. @Simon-Rey

https://github.com/voting-tools/pref_voting/blob/3da023508de791abec895f643eb2167c3501ee71/pref_voting/generate_profiles.py#L25
https://github.com/voting-tools/pref_voting/blob/3da023508de791abec895f643eb2167c3501ee71/pref_voting/generate_profiles.py#L401-L406

**Comment by epacuit** [comment]
Thanks.   I'll update this to use the latest code (point_samplers, etc.)

**Comment by DominikPeters** [comment]
Cool, thanks. Perhaps worth waiting a few days, I asked Simon whether it would be possible to provide a more straightforward interface for specifying 2D spheres etc. within `prefsampling`
