### ISSUE TITLE
[Feature Request] Participation violations

### ISSUE THREAD

**Issue by ParadaCarleton** [voting-tools/pref_voting#87]
Hi! First, I just wanted to say thank you for all your hard work on this!

I'd love having a way to check for violations of participation in this package—I'm trying to measure rates of various criteria failures for different systems. Thanks!

**Comment by wesholliday** [comment]
Thanks! We will get participation implemented ASAP.

**Comment by ParadaCarleton** [comment]
> Will you test for violations of coalitional participation or just single-voter participation?

I'm not sure what you mean here; I'm looking for situations where a candidate is defeated as a result of having "too many supporters". (i.e. there's a subset of the electorate who prefer A to B, but adding their votes into the pile changes the winner from B to A.)

**Comment by wesholliday** [comment]
Got it--that's the coalitional version of the axiom. Thanks!

**Comment by wesholliday** [comment]
@ParadaCarleton , you can now check for participation violations using has_participation_violation and find_all_participation_violations (see https://pref-voting.readthedocs.io/en/latest/variable_voter_axioms.html#participation). I suggest testing these thoroughly before using them for research purposes.
